# Generated by Django 3.0.6 on 2021-02-16 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210216_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
